### PR TITLE
fix: clone payload before passing it to before or after hooks running in the main thread

### LINKED ISSUE #1263: Issue when using csv payload in latest version
image
When try to load a payload from csv the console throw this error

Node version: v16.11.1

### PR DESCRIPTION
**Pull request by flentini**
fixes #1263

### CODE REVIEW

File: lib/launch-local.js [hunk 1]
```diff
@@ -172,7 +173,7 @@ class Launcher {
       return {};
     }
 
-    const runnableScript = prepareScript(this.script, this.payload, this.opts);
+    const runnableScript = prepareScript(this.script, _.cloneDeep(this.payload), this.opts);
```
Comment (hassy) [inline lib/launch-local.js:176]: any reason not to clone `payload` inside `prepareScript`?

Comment (flentini) [reply lib/launch-local.js:176]: `prepareScript` is called by each worker, and by the time we are there the payload is already a copy so cloning it seemed redundant. it only needs to be cloned when the main thread uses it
